[package]
name = "project_2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow="1.0"
rand = "0.8"
crossterm = "0.23"
prettytable-rs = "0.8.0"
colored = "1.9.3"